name: Create pre-release
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */1 * * *' # run every 6 hours
  push:
    branches:
      - dev
    paths:
      - 'scripts/**'

jobs:
  create_pre-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: dev
      
      - name: Create pre-release
        id: create_pre-release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          tag_name: pre-release
          release_name: pre-release
          prerelease: true
          draft: false
