name: Create Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'scripts/**'
      - 'VERSION'

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get version number
        id: version
        run: echo "::set-output name=version::$(cat VERSION)"

      - name: Create release
        id: create_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.version }}
          release_name: Release ${{ steps.version.outputs.version }}
          draft: false
          prerelease: false

      - name: Generate checksums
        run: |
          for file in scripts/*.py; do
            sha256sum "$file" > "$file.sha256"
          done

      - name: Upload release assets
        id: upload-release-assets
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./scripts/*.py
          asset_name: ${{ env.FILE_NAME }}
          asset_content_type: text/x-python-script
      - name: Upload release asset checksums
        id: upload-release-asset-checksums
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./scripts/*.sha256
          asset_name: ${{ env.FILE_NAME }}.sha256
          asset_content_type: text/plain
