name: Create pre-release
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */1 * * *' # run every 6 hours
  push:
    branches:
      - dev
    paths:
      - 'scripts/**'

jobs:
  create_pre-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: dev
      
      - name: Get short commit hash
        id: get_sha
        run: echo "::set-output name=sha_short::$(git log -1 --format=%h)"
          
      - name: Create pre-release
        id: create_pre-release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          tag_name: "pre-release_${{ steps.get_sha.outputs.sha_short }}"
          release_name: "pre-release"
          prerelease: true
          draft: false
          
      - name: Upload pre-release asset1
        id: upload-pre_release-asset1
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_pre-release.outputs.upload_url }}
          asset_path: ./scripts/hashcalculator_csv.py
          asset_name: hashcalculator_csv.py
          asset_content_type: text/x-python-script
          
      - name: Upload pre-release asset2
        id: upload-pre_release-asset2
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_pre-release.outputs.upload_url }}
          asset_path: ./scripts/hashcalculator_sql.py
          asset_name: hashcalculator_sql.py
          asset_content_type: text/x-python-script
          
      - name: Upload pre-release asset3
        id: upload-pre_release-asset3
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_pre-release.outputs.upload_url }}
          asset_path: ./scripts/hashcalculator_txt.py
          asset_name: hashcalculator_txt.py
          asset_content_type: text/x-python-script
